name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH and run tests
        run: |
          export PYTHONPATH=$(pwd)/app
          pytest
          
  cd:
    name: Build & Push Docker Image
    needs: ci  # Only runs if tests pass
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          REPO_OWNER=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_OWNER/fastapi-ci-cd:latest .

      - name: Push Docker Image to GHCR
        run: |
          REPO_OWNER=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_OWNER/fastapi-ci-cd:latest

      - name: Logout from GHCR
        run: docker logout ghcr.io
